publications:
    - name: prod
      suffix: ""
      server: sftp://uploader@package-upload.edgedb.net:22/

targets:
    linux:
        - name: linux-aarch64-00
          arch: aarch64
          platform: linux
          platform_version: aarch64
          family: generic
          runs_on: [package-builder, self-hosted, linux, arm64]
        - name: linux-aarch64-01
          arch: aarch64
          platform: linux
          platform_version: aarch64
          family: generic
          runs_on: [package-builder, self-hosted, linux, arm64]
        - name: linux-aarch64-02
          arch: aarch64
          platform: linux
          platform_version: aarch64
          family: generic
          runs_on: [package-builder, self-hosted, linux, arm64]
        - name: linux-aarch64-03
          arch: aarch64
          platform: linux
          platform_version: aarch64
          family: generic
          runs_on: [package-builder, self-hosted, linux, arm64]
        - name: linux-aarch64-04
          arch: aarch64
          platform: linux
          platform_version: aarch64
          family: generic
          runs_on: [package-builder, self-hosted, linux, arm64]
        - name: linux-aarch64-05
          arch: aarch64
          platform: linux
          platform_version: aarch64
          family: generic
          runs_on: [package-builder, self-hosted, linux, arm64]
        - name: linux-aarch64-06
          arch: aarch64
          platform: linux
          platform_version: aarch64
          family: generic
          runs_on: [package-builder, self-hosted, linux, arm64]
        - name: linux-aarch64-07
          arch: aarch64
          platform: linux
          platform_version: aarch64
          family: generic
          runs_on: [package-builder, self-hosted, linux, arm64]
        - name: linux-aarch64-08
          arch: aarch64
          platform: linux
          platform_version: aarch64
          family: generic
          runs_on: [package-builder, self-hosted, linux, arm64]
        - name: linux-aarch64-09
          arch: aarch64
          platform: linux
          platform_version: aarch64
          family: generic
          runs_on: [package-builder, self-hosted, linux, arm64]
    macos: []
