targets:
    linux:
        - name: debian-stretch
          platform: debian
          platform_version: stretch
          family: debian
        - name: debian-buster
          platform: debian
          platform_version: buster
          family: debian
        - name: ubuntu-xenial
          platform: ubuntu
          platform_version: xenial
          family: debian
        - name: ubuntu-bionic
          platform: ubuntu
          platform_version: bionic
          family: debian
        - name: ubuntu-focal
          platform: ubuntu
          platform_version: focal
          family: debian
        - name: centos-7
          platform: centos
          platform_version: 7
          family: redhat
        - name: centos-8
          platform: centos
          platform_version: 8
          family: redhat

    macos:
        - name: macos-x86_64
          platform: macos
          platform_version: x86_64
          family: macos
