<% from "build.inc.yml" import workflow -%>
name: Build Test and Publish a Release

on:
  workflow_dispatch:
    inputs: {}

jobs:
  <<- workflow(targets, publications, subdist="", publish_all=True) ->>
