name: Build Test and Publish a Release

on:
  workflow_dispatch:
    inputs: {}

jobs:
  prep:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.whichver.outputs.branch }}
    steps:
    - uses: actions/checkout@v2

    - name: Determine package version
      shell: bash
      run: |
        branch=${GITHUB_REF#refs/heads/}
        echo ::set-output name=branch::"${branch}"
      id: whichver

<% for tgt in targets.linux %>
  build-<< tgt.name >>:
    runs-on: ubuntu-latest
    needs: prep

    steps:
    - name: Build
      uses: edgedb/edgedb-pkg/integration/linux/build/<< tgt.name >>@master
      env:
        SRC_REF: "${{ needs.prep.outputs.branch }}"
        PKG_REVISION: "<current-date>"
        PKG_PLATFORM: "<< tgt.platform >>"
        PKG_PLATFORM_VERSION: "<< tgt.platform_version >>"
        EXTRA_OPTIMIZATIONS: "true"
        BUILD_IS_RELEASE: "true"
<% if tgt.family == "generic" %>
        BUILD_GENERIC: true
<% endif %>
<% if tgt.platform_libc %>
        PKG_PLATFORM_LIBC: "<< tgt.platform_libc >>"
<% endif %>

    - uses: actions/upload-artifact@v2
      with:
        name: builds-<< tgt.name >>
        path: artifacts/<< tgt.name >>
<% endfor %>
<% for tgt in targets.macos %>
  build-<< tgt.name >>:
    runs-on: macos-latest
    needs: prep

    steps:
    - uses: actions/checkout@v2
      with:
        repository: edgedb/edgedb-pkg
        ref: master
        path: edgedb-pkg

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        default: true

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Build
      env:
        SRC_REF: "${{ needs.prep.outputs.branch }}"
        BUILD_IS_RELEASE: "true"
        PKG_REVISION: "<current-date>"
        PKG_PLATFORM: "<< tgt.platform >>"
        PKG_PLATFORM_VERSION: "<< tgt.platform_version >>"
      run: |
        edgedb-pkg/integration/macos/build.sh

    - uses: actions/upload-artifact@v1
      with:
        name: builds-<< tgt.name >>
        path: artifacts/<< tgt.name >>
<% endfor %>
<% for tgt in targets.linux %>
  test-<< tgt.name >>:
    needs: [build-<< tgt.name >>]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: builds-<< tgt.name >>
        path: artifacts/<< tgt.name >>

    - name: Test
      uses: edgedb/edgedb-pkg/integration/linux/test/<< tgt.name >>@master
      env:
        PKG_PLATFORM: "<< tgt.platform >>"
        PKG_PLATFORM_VERSION: "<< tgt.platform_version >>"
        # edb test with -j higher than 1 seems to result in workflow
        # jobs getting killed arbitrarily by Github.
        PKG_TEST_JOBS: 1

<% endfor %>
<% for tgt in targets.macos %>
  test-<< tgt.name >>:
    needs: [build-<< tgt.name >>]
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: edgedb/edgedb-pkg
        ref: master
        path: edgedb-pkg

    - uses: actions/download-artifact@v2
      with:
        name: builds-<< tgt.name >>
        path: artifacts/<< tgt.name >>

    - name: Test
      env:
        PKG_PLATFORM: "<< tgt.platform >>"
        PKG_PLATFORM_VERSION: "<< tgt.platform_version >>"
      run: |
        edgedb-pkg/integration/macos/test.sh
<% endfor %>
<% for tgt in targets.linux %>
  publish-<< tgt.name >>:
    needs: [test-<< tgt.name >>]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: builds-<< tgt.name >>
        path: artifacts/<< tgt.name >>

    - name: Describe
      id: describe
      uses: edgedb/edgedb-pkg/integration/actions/describe-artifact@master
      with:
        target: << tgt.name >>

    - name: Publish
      uses: edgedb/edgedb-pkg/integration/linux/upload/<< tgt.platform >><< "-{}".format(tgt.platform_version) if tgt.platform_version >>@master
      env:
        PKG_PLATFORM: "<< tgt.platform >>"
        PKG_PLATFORM_VERSION: "<< tgt.platform_version >>"
        PACKAGE_UPLOAD_SSH_KEY: "${{ secrets.PACKAGE_UPLOAD_SSH_KEY }}"

    - name: Test Published
      uses: edgedb/edgedb-pkg/integration/linux/testpublished/<< tgt.name >>@master
      env:
        PKG_PLATFORM: "<< tgt.platform >>"
        PKG_PLATFORM_VERSION: "<< tgt.platform_version >>"
        PKG_INSTALL_REF: "${{ steps.describe.outputs.install-ref }}"
        PKG_VERSION_SLOT: "${{ steps.describe.outputs.version-slot }}"

    <% if tgt.name == 'debian-buster' %>
    - uses: actions/checkout@v2
      with:
        repository: edgedb/edgedb-docker
        ref: master
        path: dockerfile
    - name: Publish Docker Image
      uses: elgohr/Publish-Docker-Github-Action@3.04
      with:
        name: edgedb/edgedb
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: ${{ steps.describe.outputs.version-slot }}
        workdir: dockerfile
        buildargs: version=${{ steps.describe.outputs.version-slot }}
    <% endif %>
<% endfor %>
<% for tgt in targets.macos %>
  publish-<< tgt.name >>:
    needs: [test-<< tgt.name >>]
    runs-on: macos-latest

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: builds-<< tgt.name >>
        path: artifacts/<< tgt.name >>

    - uses: actions/checkout@v2
      with:
        repository: edgedb/edgedb-pkg
        ref: master
        path: edgedb-pkg

    - name: Describe
      id: describe
      uses: edgedb/edgedb-pkg/integration/actions/describe-artifact@master
      with:
        target: << tgt.name >>

    - name: Publish
      env:
        PKG_PLATFORM: "<< tgt.platform >>"
        PKG_PLATFORM_VERSION: "<< tgt.platform_version >>"
        PACKAGE_UPLOAD_SSH_KEY: "${{ secrets.PACKAGE_UPLOAD_SSH_KEY }}"
      run: |
        edgedb-pkg/integration/macos/publish.sh
<% endfor %>
