<% from "tests.inc.yml" import build, calc_cache_key -%>

name: Pool Simulation Test

on:
  push:
    branches:
      - master
      - pool-test
    paths:
      - 'edb/server/connpool/**'
      - 'edb/server/conn_pool/**'
      - 'tests/test_server_pool.py'
      - '.github/workflows/tests-pool.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'edb/server/connpool/**'
      - 'edb/server/conn_pool/**'
      - 'tests/test_server_pool.py'
      - '.github/workflows/tests-pool.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    concurrency: pool-test
    steps:
    <%- call build() -%>
    - name: Compute cache keys
      run: |
        << calc_cache_key()|indent >>
    <%- endcall %>

    - uses: actions/checkout@v4
      if: startsWith(github.ref, 'refs/heads')
      with:
        repository: edgedb/edgedb-pool-simulation
        path: pool-simulation
        token: ${{ secrets.GITHUB_CI_BOT_TOKEN }}

    - name: Run the pool simulation test
      env:
        PYTHONPATH: .
        SIMULATION_CI: yes
        TIME_SCALE: 10
      run: |
        mkdir -p pool-simulation/reports
        python tests/test_server_pool.py

    - uses: EndBug/add-and-commit@v7.0.0
      if: ${{ always() }}
      continue-on-error: true
      with:
        branch: main
        cwd: pool-simulation
        author_name: github-actions
        author_email: 41898282+github-actions[bot]@users.noreply.github.com
