---
name: Bug report
about: Create a report to help us improve
---
<!-- Please search existing issues to avoid creating duplicates. -->
- EdgeDB Version:
- OS Version:

Steps to Reproduce:

1.
2.

<!-- If the issue is about a query error, please also provide your schema -->
Schema:
