---
name: Feature request
about: Suggest a feature for EdgeDB

---

<!-- Please search existing issues to avoid creating duplicates. -->

<!-- Describe the feature you'd like to see implemented in EdgeDB. -->
