# AUTOGENERATED FROM "edb/api/types.txt" WITH
#    $ edb gen-types


import uuid


TYPE_IDS = {
    'anytype': uuid.UUID('00000000-0000-0000-0000-000000000001'),
    'anytuple': uuid.UUID('00000000-0000-0000-0000-000000000002'),
    'empty-tuple': uuid.UUID('00000000-0000-0000-0000-0000000000ff'),
    'std::uuid': uuid.UUID('00000000-0000-0000-0000-000000000100'),
    'std::str': uuid.UUID('00000000-0000-0000-0000-000000000101'),
    'std::bytes': uuid.UUID('00000000-0000-0000-0000-000000000102'),
    'std::int16': uuid.UUID('00000000-0000-0000-0000-000000000103'),
    'std::int32': uuid.UUID('00000000-0000-0000-0000-000000000104'),
    'std::int64': uuid.UUID('00000000-0000-0000-0000-000000000105'),
    'std::float32': uuid.UUID('00000000-0000-0000-0000-000000000106'),
    'std::float64': uuid.UUID('00000000-0000-0000-0000-000000000107'),
    'std::decimal': uuid.UUID('00000000-0000-0000-0000-000000000108'),
    'std::bool': uuid.UUID('00000000-0000-0000-0000-000000000109'),
    'std::datetime': uuid.UUID('00000000-0000-0000-0000-00000000010a'),
    'std::naive_datetime': uuid.UUID('00000000-0000-0000-0000-00000000010b'),
    'std::naive_date': uuid.UUID('00000000-0000-0000-0000-00000000010c'),
    'std::naive_time': uuid.UUID('00000000-0000-0000-0000-00000000010d'),
    'std::timedelta': uuid.UUID('00000000-0000-0000-0000-00000000010e'),
    'std::json': uuid.UUID('00000000-0000-0000-0000-00000000010f'),
}
