# AUTOGENERATED FROM "edb/api/types.txt" WITH
#    $ edb gen-types


from __future__ import annotations

from edb.common import uuidgen


TYPE_IDS = {
    'anytype': uuidgen.UUID('00000000-0000-0000-0000-000000000001'),
    'anytuple': uuidgen.UUID('00000000-0000-0000-0000-000000000002'),
    'std': uuidgen.UUID('00000000-0000-0000-0000-0000000000f0'),
    'empty-tuple': uuidgen.UUID('00000000-0000-0000-0000-0000000000ff'),
    'std::uuid': uuidgen.UUID('00000000-0000-0000-0000-000000000100'),
    'std::str': uuidgen.UUID('00000000-0000-0000-0000-000000000101'),
    'std::bytes': uuidgen.UUID('00000000-0000-0000-0000-000000000102'),
    'std::int16': uuidgen.UUID('00000000-0000-0000-0000-000000000103'),
    'std::int32': uuidgen.UUID('00000000-0000-0000-0000-000000000104'),
    'std::int64': uuidgen.UUID('00000000-0000-0000-0000-000000000105'),
    'std::float32': uuidgen.UUID('00000000-0000-0000-0000-000000000106'),
    'std::float64': uuidgen.UUID('00000000-0000-0000-0000-000000000107'),
    'std::decimal': uuidgen.UUID('00000000-0000-0000-0000-000000000108'),
    'std::bool': uuidgen.UUID('00000000-0000-0000-0000-000000000109'),
    'std::datetime': uuidgen.UUID('00000000-0000-0000-0000-00000000010a'),
    'std::local_datetime': uuidgen.UUID(
        '00000000-0000-0000-0000-00000000010b'
    ),
    'std::local_date': uuidgen.UUID('00000000-0000-0000-0000-00000000010c'),
    'std::local_time': uuidgen.UUID('00000000-0000-0000-0000-00000000010d'),
    'std::duration': uuidgen.UUID('00000000-0000-0000-0000-00000000010e'),
    'std::json': uuidgen.UUID('00000000-0000-0000-0000-00000000010f'),
}
