name: Docs Preview Deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        env:
          VERCEL_TOKEN: secrets.VERCEL_TOKEN
          VERCEL_TEAM_ID: secrets.VERCEL_TEAM_ID
        with:
          script: |
            const res = await fetch(`https://api.vercel.com/v13/deployments?teamId=${process.env.VERCEL_TEAM_ID}`, {
              "body": {
                name: "edgedb-docs",
                gitSource: {
                  type: "github",
                  org: "edgedb",
                  repo: "edgedb.com",
                  ref: "docs-preview",
                },
                projectSettings: {
                  buildCommand:
                    `EDGEDB_REPO_BRANCH=${process.env.GITHUB_REF_NAME} yarn vercel-build`,
                },
              },
              "headers": {
                "Authorization": `Bearer ${process.env.VERCEL_TOKEN}`
              },
              "method": "post"
            });

            if (res.ok) {
              const deployment = await res.json();
              console.log(deployment.url);
            } else {
              throw new Error(
                `vercel create deployment api request failed: ${res.status} ${res.statusText}`
              );
            }
