name: Docs Preview Deploy

on:
  pull_request:
    paths:
      - "docs/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }}
        with:
          script: |
            const script = require('./.github/scripts/docs/preview-deploy.js');
            await script({github, context});
