name: Build Test and Publish a Release

on:
  workflow_dispatch:
    inputs: {}

jobs:

  build-debian-stretch:
    runs-on: ubuntu-latest

    steps:
    - name: Determine package version
      shell: bash
      run: |
        echo ::set-output name=branch::${GITHUB_REF#refs/heads/}
        echo ::set-output name=version::${GITHUB_REF#refs/heads/releases/}
      id: whichver

    - name: Build
      uses: edgedb/edgedb-pkg/integration/linux/build/debian-stretch@master
      env:
        SRC_REF: "${{ steps.whichver.outputs.branch }}"
        PKG_VERSION: "${{ steps.whichver.outputs.version }}"
        PKG_REVISION: "<current-date>"
        PKG_PLATFORM: "debian"
        PKG_PLATFORM_VERSION: "stretch"
        EXTRA_OPTIMIZATIONS: "true"

    - uses: actions/upload-artifact@v2
      with:
        name: builds-debian-stretch
        path: artifacts/debian-stretch

  build-debian-buster:
    runs-on: ubuntu-latest

    steps:
    - name: Determine package version
      shell: bash
      run: |
        echo ::set-output name=branch::${GITHUB_REF#refs/heads/}
        echo ::set-output name=version::${GITHUB_REF#refs/heads/releases/}
      id: whichver

    - name: Build
      uses: edgedb/edgedb-pkg/integration/linux/build/debian-buster@master
      env:
        SRC_REF: "${{ steps.whichver.outputs.branch }}"
        PKG_VERSION: "${{ steps.whichver.outputs.version }}"
        PKG_REVISION: "<current-date>"
        PKG_PLATFORM: "debian"
        PKG_PLATFORM_VERSION: "buster"
        EXTRA_OPTIMIZATIONS: "true"

    - uses: actions/upload-artifact@v2
      with:
        name: builds-debian-buster
        path: artifacts/debian-buster

  build-ubuntu-xenial:
    runs-on: ubuntu-latest

    steps:
    - name: Determine package version
      shell: bash
      run: |
        echo ::set-output name=branch::${GITHUB_REF#refs/heads/}
        echo ::set-output name=version::${GITHUB_REF#refs/heads/releases/}
      id: whichver

    - name: Build
      uses: edgedb/edgedb-pkg/integration/linux/build/ubuntu-xenial@master
      env:
        SRC_REF: "${{ steps.whichver.outputs.branch }}"
        PKG_VERSION: "${{ steps.whichver.outputs.version }}"
        PKG_REVISION: "<current-date>"
        PKG_PLATFORM: "ubuntu"
        PKG_PLATFORM_VERSION: "xenial"
        EXTRA_OPTIMIZATIONS: "true"

    - uses: actions/upload-artifact@v2
      with:
        name: builds-ubuntu-xenial
        path: artifacts/ubuntu-xenial

  build-ubuntu-bionic:
    runs-on: ubuntu-latest

    steps:
    - name: Determine package version
      shell: bash
      run: |
        echo ::set-output name=branch::${GITHUB_REF#refs/heads/}
        echo ::set-output name=version::${GITHUB_REF#refs/heads/releases/}
      id: whichver

    - name: Build
      uses: edgedb/edgedb-pkg/integration/linux/build/ubuntu-bionic@master
      env:
        SRC_REF: "${{ steps.whichver.outputs.branch }}"
        PKG_VERSION: "${{ steps.whichver.outputs.version }}"
        PKG_REVISION: "<current-date>"
        PKG_PLATFORM: "ubuntu"
        PKG_PLATFORM_VERSION: "bionic"
        EXTRA_OPTIMIZATIONS: "true"

    - uses: actions/upload-artifact@v2
      with:
        name: builds-ubuntu-bionic
        path: artifacts/ubuntu-bionic

  build-ubuntu-focal:
    runs-on: ubuntu-latest

    steps:
    - name: Determine package version
      shell: bash
      run: |
        echo ::set-output name=branch::${GITHUB_REF#refs/heads/}
        echo ::set-output name=version::${GITHUB_REF#refs/heads/releases/}
      id: whichver

    - name: Build
      uses: edgedb/edgedb-pkg/integration/linux/build/ubuntu-focal@master
      env:
        SRC_REF: "${{ steps.whichver.outputs.branch }}"
        PKG_VERSION: "${{ steps.whichver.outputs.version }}"
        PKG_REVISION: "<current-date>"
        PKG_PLATFORM: "ubuntu"
        PKG_PLATFORM_VERSION: "focal"
        EXTRA_OPTIMIZATIONS: "true"

    - uses: actions/upload-artifact@v2
      with:
        name: builds-ubuntu-focal
        path: artifacts/ubuntu-focal

  build-centos-7:
    runs-on: ubuntu-latest

    steps:
    - name: Determine package version
      shell: bash
      run: |
        echo ::set-output name=branch::${GITHUB_REF#refs/heads/}
        echo ::set-output name=version::${GITHUB_REF#refs/heads/releases/}
      id: whichver

    - name: Build
      uses: edgedb/edgedb-pkg/integration/linux/build/centos-7@master
      env:
        SRC_REF: "${{ steps.whichver.outputs.branch }}"
        PKG_VERSION: "${{ steps.whichver.outputs.version }}"
        PKG_REVISION: "<current-date>"
        PKG_PLATFORM: "centos"
        PKG_PLATFORM_VERSION: "7"
        EXTRA_OPTIMIZATIONS: "true"

    - uses: actions/upload-artifact@v2
      with:
        name: builds-centos-7
        path: artifacts/centos-7

  build-centos-8:
    runs-on: ubuntu-latest

    steps:
    - name: Determine package version
      shell: bash
      run: |
        echo ::set-output name=branch::${GITHUB_REF#refs/heads/}
        echo ::set-output name=version::${GITHUB_REF#refs/heads/releases/}
      id: whichver

    - name: Build
      uses: edgedb/edgedb-pkg/integration/linux/build/centos-8@master
      env:
        SRC_REF: "${{ steps.whichver.outputs.branch }}"
        PKG_VERSION: "${{ steps.whichver.outputs.version }}"
        PKG_REVISION: "<current-date>"
        PKG_PLATFORM: "centos"
        PKG_PLATFORM_VERSION: "8"
        EXTRA_OPTIMIZATIONS: "true"

    - uses: actions/upload-artifact@v2
      with:
        name: builds-centos-8
        path: artifacts/centos-8


  build-macos-x86_64:
    runs-on: macos-latest

    steps:
    - name: Determine package version
      shell: bash
      run: |
        echo ::set-output name=branch::${GITHUB_REF#refs/heads/}
        echo ::set-output name=version::${GITHUB_REF#refs/heads/releases/}
      id: whichver

    - uses: actions/checkout@v2
      with:
        repository: edgedb/edgedb-pkg
        ref: master
        path: edgedb-pkg

    - uses: actions/cache@v2
      id: sdk1010cache
      with:
        path: ~/.cache/MacOSX10.10.sdk/
        key: MacOSX10.10.sdk

    - name: Install Xcode
      if: steps.sdk1010cache.outputs.cache-hit != 'true'
      env:
        XCODE_INSTALL_USER: github-ci@edgedb.com
        XCODE_INSTALL_PASSWORD: ${{ secrets.BOT_APPLE_ID_PASSWORD }}
        SPACESHIP_SKIP_2FA_UPGRADE: 1
      run: |
        xcversion install 6.4

    - name: Cache 10.10 SDK
      if: steps.sdk1010cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p ~/.cache
        cp -a \
          /Applications/Xcode-6.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/ \
          ~/.cache/MacOSX10.10.sdk/

    - name: Select macOS SDK
      run: |
        sudo cp -a \
          ~/.cache/MacOSX10.10.sdk/ \
          /Library/Developer/CommandLineTools/SDKs/MacOSX10.10.sdk/
        sudo xcode-select -s /Library/Developer/CommandLineTools

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        default: true

    - name: Build
      env:
        SRC_REF: "${{ steps.whichver.outputs.branch }}"
        PKG_VERSION: "${{ steps.whichver.outputs.version }}"
        PKG_REVISION: "<current-date>"
        PKG_PLATFORM: "macos"
        PKG_PLATFORM_VERSION: "x86_64"
        SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX10.10.sdk/
      run: |
        edgedb-pkg/integration/macos/build.sh

    - uses: actions/upload-artifact@v1
      with:
        name: builds-macos-x86_64
        path: artifacts/macos-x86_64


  test-debian-stretch:
    needs: [build-debian-stretch]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: builds-debian-stretch
        path: artifacts/debian-stretch

    - name: Test
      uses: edgedb/edgedb-pkg/integration/linux/test/debian-stretch@master
      env:
        PKG_PLATFORM: "debian"
        PKG_PLATFORM_VERSION: "stretch"


  test-debian-buster:
    needs: [build-debian-buster]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: builds-debian-buster
        path: artifacts/debian-buster

    - name: Test
      uses: edgedb/edgedb-pkg/integration/linux/test/debian-buster@master
      env:
        PKG_PLATFORM: "debian"
        PKG_PLATFORM_VERSION: "buster"


  test-ubuntu-xenial:
    needs: [build-ubuntu-xenial]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: builds-ubuntu-xenial
        path: artifacts/ubuntu-xenial

    - name: Test
      uses: edgedb/edgedb-pkg/integration/linux/test/ubuntu-xenial@master
      env:
        PKG_PLATFORM: "ubuntu"
        PKG_PLATFORM_VERSION: "xenial"


  test-ubuntu-bionic:
    needs: [build-ubuntu-bionic]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: builds-ubuntu-bionic
        path: artifacts/ubuntu-bionic

    - name: Test
      uses: edgedb/edgedb-pkg/integration/linux/test/ubuntu-bionic@master
      env:
        PKG_PLATFORM: "ubuntu"
        PKG_PLATFORM_VERSION: "bionic"


  test-ubuntu-focal:
    needs: [build-ubuntu-focal]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: builds-ubuntu-focal
        path: artifacts/ubuntu-focal

    - name: Test
      uses: edgedb/edgedb-pkg/integration/linux/test/ubuntu-focal@master
      env:
        PKG_PLATFORM: "ubuntu"
        PKG_PLATFORM_VERSION: "focal"


  test-centos-7:
    needs: [build-centos-7]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: builds-centos-7
        path: artifacts/centos-7

    - name: Test
      uses: edgedb/edgedb-pkg/integration/linux/test/centos-7@master
      env:
        PKG_PLATFORM: "centos"
        PKG_PLATFORM_VERSION: "7"


  test-centos-8:
    needs: [build-centos-8]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: builds-centos-8
        path: artifacts/centos-8

    - name: Test
      uses: edgedb/edgedb-pkg/integration/linux/test/centos-8@master
      env:
        PKG_PLATFORM: "centos"
        PKG_PLATFORM_VERSION: "8"



  test-macos-x86_64:
    needs: [build-macos-x86_64]
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: edgedb/edgedb-pkg
        ref: master
        path: edgedb-pkg

    - uses: actions/download-artifact@v2
      with:
        name: builds-macos-x86_64
        path: artifacts/macos-x86_64

    - name: Test
      env:
        PKG_PLATFORM: "macos"
        PKG_PLATFORM_VERSION: "x86_64"
      run: |
        edgedb-pkg/integration/macos/test.sh


  publish-debian-stretch:
    needs: [test-debian-stretch]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: builds-debian-stretch
        path: artifacts/debian-stretch

    - name: Describe
      id: describe
      uses: edgedb/edgedb-pkg/integration/actions/describe-artifact@master
      with:
        target: debian-stretch

    - name: Publish
      uses: edgedb/edgedb-pkg/integration/linux/upload/debian-stretch@master
      env:
        PKG_PLATFORM: "debian"
        PKG_PLATFORM_VERSION: "stretch"
        PKG_VERSION_SLOT: "${{ steps.describe.outputs.version-slot }}"
        PACKAGE_UPLOAD_SSH_KEY: "${{ secrets.PACKAGE_UPLOAD_SSH_KEY }}"

    - name: Test Published
      uses: edgedb/edgedb-pkg/integration/linux/testpublished/debian-stretch@master
      env:
        PKG_PLATFORM: "debian"
        PKG_PLATFORM_VERSION: "stretch"
        PKG_VERSION_SLOT: "${{ steps.describe.outputs.version-slot }}"

    

  publish-debian-buster:
    needs: [test-debian-buster]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: builds-debian-buster
        path: artifacts/debian-buster

    - name: Describe
      id: describe
      uses: edgedb/edgedb-pkg/integration/actions/describe-artifact@master
      with:
        target: debian-buster

    - name: Publish
      uses: edgedb/edgedb-pkg/integration/linux/upload/debian-buster@master
      env:
        PKG_PLATFORM: "debian"
        PKG_PLATFORM_VERSION: "buster"
        PKG_VERSION_SLOT: "${{ steps.describe.outputs.version-slot }}"
        PACKAGE_UPLOAD_SSH_KEY: "${{ secrets.PACKAGE_UPLOAD_SSH_KEY }}"

    - name: Test Published
      uses: edgedb/edgedb-pkg/integration/linux/testpublished/debian-buster@master
      env:
        PKG_PLATFORM: "debian"
        PKG_PLATFORM_VERSION: "buster"
        PKG_VERSION_SLOT: "${{ steps.describe.outputs.version-slot }}"

    
    - uses: actions/checkout@v2
      with:
        repository: edgedb/edgedb-docker
        ref: master
        path: dockerfile
    - name: Publish Docker Image
      uses: elgohr/Publish-Docker-Github-Action@2.6
      with:
        name: edgedb/edgedb:${{ steps.describe.outputs.version-slot }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        snapshot: true
        workdir: dockerfile
        buildargs: version=${{ steps.describe.outputs.version-slot }}
    

  publish-ubuntu-xenial:
    needs: [test-ubuntu-xenial]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: builds-ubuntu-xenial
        path: artifacts/ubuntu-xenial

    - name: Describe
      id: describe
      uses: edgedb/edgedb-pkg/integration/actions/describe-artifact@master
      with:
        target: ubuntu-xenial

    - name: Publish
      uses: edgedb/edgedb-pkg/integration/linux/upload/ubuntu-xenial@master
      env:
        PKG_PLATFORM: "ubuntu"
        PKG_PLATFORM_VERSION: "xenial"
        PKG_VERSION_SLOT: "${{ steps.describe.outputs.version-slot }}"
        PACKAGE_UPLOAD_SSH_KEY: "${{ secrets.PACKAGE_UPLOAD_SSH_KEY }}"

    - name: Test Published
      uses: edgedb/edgedb-pkg/integration/linux/testpublished/ubuntu-xenial@master
      env:
        PKG_PLATFORM: "ubuntu"
        PKG_PLATFORM_VERSION: "xenial"
        PKG_VERSION_SLOT: "${{ steps.describe.outputs.version-slot }}"

    

  publish-ubuntu-bionic:
    needs: [test-ubuntu-bionic]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: builds-ubuntu-bionic
        path: artifacts/ubuntu-bionic

    - name: Describe
      id: describe
      uses: edgedb/edgedb-pkg/integration/actions/describe-artifact@master
      with:
        target: ubuntu-bionic

    - name: Publish
      uses: edgedb/edgedb-pkg/integration/linux/upload/ubuntu-bionic@master
      env:
        PKG_PLATFORM: "ubuntu"
        PKG_PLATFORM_VERSION: "bionic"
        PKG_VERSION_SLOT: "${{ steps.describe.outputs.version-slot }}"
        PACKAGE_UPLOAD_SSH_KEY: "${{ secrets.PACKAGE_UPLOAD_SSH_KEY }}"

    - name: Test Published
      uses: edgedb/edgedb-pkg/integration/linux/testpublished/ubuntu-bionic@master
      env:
        PKG_PLATFORM: "ubuntu"
        PKG_PLATFORM_VERSION: "bionic"
        PKG_VERSION_SLOT: "${{ steps.describe.outputs.version-slot }}"

    

  publish-ubuntu-focal:
    needs: [test-ubuntu-focal]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: builds-ubuntu-focal
        path: artifacts/ubuntu-focal

    - name: Describe
      id: describe
      uses: edgedb/edgedb-pkg/integration/actions/describe-artifact@master
      with:
        target: ubuntu-focal

    - name: Publish
      uses: edgedb/edgedb-pkg/integration/linux/upload/ubuntu-focal@master
      env:
        PKG_PLATFORM: "ubuntu"
        PKG_PLATFORM_VERSION: "focal"
        PKG_VERSION_SLOT: "${{ steps.describe.outputs.version-slot }}"
        PACKAGE_UPLOAD_SSH_KEY: "${{ secrets.PACKAGE_UPLOAD_SSH_KEY }}"

    - name: Test Published
      uses: edgedb/edgedb-pkg/integration/linux/testpublished/ubuntu-focal@master
      env:
        PKG_PLATFORM: "ubuntu"
        PKG_PLATFORM_VERSION: "focal"
        PKG_VERSION_SLOT: "${{ steps.describe.outputs.version-slot }}"

    

  publish-centos-7:
    needs: [test-centos-7]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: builds-centos-7
        path: artifacts/centos-7

    - name: Describe
      id: describe
      uses: edgedb/edgedb-pkg/integration/actions/describe-artifact@master
      with:
        target: centos-7

    - name: Publish
      uses: edgedb/edgedb-pkg/integration/linux/upload/centos-7@master
      env:
        PKG_PLATFORM: "centos"
        PKG_PLATFORM_VERSION: "7"
        PKG_VERSION_SLOT: "${{ steps.describe.outputs.version-slot }}"
        PACKAGE_UPLOAD_SSH_KEY: "${{ secrets.PACKAGE_UPLOAD_SSH_KEY }}"

    - name: Test Published
      uses: edgedb/edgedb-pkg/integration/linux/testpublished/centos-7@master
      env:
        PKG_PLATFORM: "centos"
        PKG_PLATFORM_VERSION: "7"
        PKG_VERSION_SLOT: "${{ steps.describe.outputs.version-slot }}"

    

  publish-centos-8:
    needs: [test-centos-8]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: builds-centos-8
        path: artifacts/centos-8

    - name: Describe
      id: describe
      uses: edgedb/edgedb-pkg/integration/actions/describe-artifact@master
      with:
        target: centos-8

    - name: Publish
      uses: edgedb/edgedb-pkg/integration/linux/upload/centos-8@master
      env:
        PKG_PLATFORM: "centos"
        PKG_PLATFORM_VERSION: "8"
        PKG_VERSION_SLOT: "${{ steps.describe.outputs.version-slot }}"
        PACKAGE_UPLOAD_SSH_KEY: "${{ secrets.PACKAGE_UPLOAD_SSH_KEY }}"

    - name: Test Published
      uses: edgedb/edgedb-pkg/integration/linux/testpublished/centos-8@master
      env:
        PKG_PLATFORM: "centos"
        PKG_PLATFORM_VERSION: "8"
        PKG_VERSION_SLOT: "${{ steps.describe.outputs.version-slot }}"

    


  publish-macos-x86_64:
    needs: [test-macos-x86_64]
    runs-on: macos-latest

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: builds-macos-x86_64
        path: artifacts/macos-x86_64

    - uses: actions/checkout@v2
      with:
        repository: edgedb/edgedb-pkg
        ref: master
        path: edgedb-pkg

    - name: Describe
      id: describe
      uses: edgedb/edgedb-pkg/integration/actions/describe-artifact@master
      with:
        target: macos-x86_64

    - name: Publish
      env:
        PKG_PLATFORM: "macos"
        PKG_PLATFORM_VERSION: "x86_64"
        PKG_VERSION_SLOT: "${{ steps.describe.outputs.version-slot }}"
        PACKAGE_UPLOAD_SSH_KEY: "${{ secrets.PACKAGE_UPLOAD_SSH_KEY }}"
      run: |
        edgedb-pkg/integration/macos/publish.sh

