name: Pool Simulation Test

on:
  push:
    branches:
      - master
      - pool-test
    paths:
      - 'edb/server/connpool/**'
      - 'tests/test_server_pool.py'
  pull_request:
    branches:
      - master
    paths:
      - 'edb/server/connpool/**'
      - 'tests/test_server_pool.py'

jobs:
  test:
    runs-on: ubuntu-latest
    concurrency: pool-test

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: false

    - uses: actions/checkout@v3
      if: startsWith(github.ref, 'refs/heads')
      with:
        repository: edgedb/edgedb-pool-simulation
        path: pool-simulation
        token: ${{ secrets.GITHUB_CI_BOT_TOKEN }}

    - name: Generate requirements.txt
      run: |
        echo 'uvloop==0.15.2' > requirements.txt
        mkdir -p pool-simulation/reports

    - name: Set up Python
      id: python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install Python dependencies
      if: ${{ !steps.python.outputs.cache-hit }}
      run: |
        pip install -r requirements.txt

    - name: Run the pool simulation test
      env:
        PYTHONPATH: .
        SIMULATION_CI: yes
        TIME_SCALE: 10
      run: |
        python tests/test_server_pool.py

    - uses: EndBug/add-and-commit@1bad3abcf0d6ec49a5857d124b0bfb52dc7bb081 # v9.1.3
      if: ${{ always() }}
      continue-on-error: true
      with:
        branch: main
        cwd: pool-simulation
        author_name: github-actions
        author_email: 41898282+github-actions[bot]@users.noreply.github.com
