#
# This source file is part of the EdgeDB open source project.
#
# Copyright 2008-present MagicStack Inc. and the EdgeDB authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

"""Declarations of information schema tables."""

from typing import *

ColumnName = str
ColumnType = str

TABLES: Dict[str, List[Tuple[ColumnName, ColumnType]]] = {
    "administrable_role_authorizations": [
        ("grantee", "sql_identifier"),
        ("role_name", "sql_identifier"),
        ("is_grantable", "yes_or_no"),
    ],
    "applicable_roles": [
        ("grantee", "sql_identifier"),
        ("role_name", "sql_identifier"),
        ("is_grantable", "yes_or_no"),
    ],
    "attributes": [
        ("udt_catalog", "sql_identifier"),
        ("udt_schema", "sql_identifier"),
        ("udt_name", "sql_identifier"),
        ("attribute_name", "sql_identifier"),
        ("ordinal_position", "cardinal_number"),
        ("attribute_default", "character_data"),
        ("is_nullable", "yes_or_no"),
        ("data_type", "character_data"),
        ("character_maximum_length", "cardinal_number"),
        ("character_octet_length", "cardinal_number"),
        ("character_set_catalog", "sql_identifier"),
        ("character_set_schema", "sql_identifier"),
        ("character_set_name", "sql_identifier"),
        ("collation_catalog", "sql_identifier"),
        ("collation_schema", "sql_identifier"),
        ("collation_name", "sql_identifier"),
        ("numeric_precision", "cardinal_number"),
        ("numeric_precision_radix", "cardinal_number"),
        ("numeric_scale", "cardinal_number"),
        ("datetime_precision", "cardinal_number"),
        ("interval_type", "character_data"),
        ("interval_precision", "cardinal_number"),
        ("attribute_udt_catalog", "sql_identifier"),
        ("attribute_udt_schema", "sql_identifier"),
        ("attribute_udt_name", "sql_identifier"),
        ("scope_catalog", "sql_identifier"),
        ("scope_schema", "sql_identifier"),
        ("scope_name", "sql_identifier"),
        ("maximum_cardinality", "cardinal_number"),
        ("dtd_identifier", "sql_identifier"),
        ("is_derived_reference_attribute", "yes_or_no"),
    ],
    "character_sets": [
        ("character_set_catalog", "sql_identifier"),
        ("character_set_schema", "sql_identifier"),
        ("character_set_name", "sql_identifier"),
        ("character_repertoire", "sql_identifier"),
        ("form_of_use", "sql_identifier"),
        ("default_collate_catalog", "sql_identifier"),
        ("default_collate_schema", "sql_identifier"),
        ("default_collate_name", "sql_identifier"),
    ],
    "check_constraint_routine_usage": [
        ("constraint_catalog", "sql_identifier"),
        ("constraint_schema", "sql_identifier"),
        ("constraint_name", "sql_identifier"),
        ("specific_catalog", "sql_identifier"),
        ("specific_schema", "sql_identifier"),
        ("specific_name", "sql_identifier"),
    ],
    "check_constraints": [
        ("constraint_catalog", "sql_identifier"),
        ("constraint_schema", "sql_identifier"),
        ("constraint_name", "sql_identifier"),
        ("check_clause", "character_data"),
    ],
    "collation_character_set_applicability": [
        ("collation_catalog", "sql_identifier"),
        ("collation_schema", "sql_identifier"),
        ("collation_name", "sql_identifier"),
        ("character_set_catalog", "sql_identifier"),
        ("character_set_schema", "sql_identifier"),
        ("character_set_name", "sql_identifier"),
    ],
    "collations": [
        ("collation_catalog", "sql_identifier"),
        ("collation_schema", "sql_identifier"),
        ("collation_name", "sql_identifier"),
        ("pad_attribute", "character_data"),
    ],
    "column_column_usage": [
        ("table_catalog", "sql_identifier"),
        ("table_schema", "sql_identifier"),
        ("table_name", "sql_identifier"),
        ("column_name", "sql_identifier"),
        ("dependent_column", "sql_identifier"),
    ],
    "column_domain_usage": [
        ("domain_catalog", "sql_identifier"),
        ("domain_schema", "sql_identifier"),
        ("domain_name", "sql_identifier"),
        ("table_catalog", "sql_identifier"),
        ("table_schema", "sql_identifier"),
        ("table_name", "sql_identifier"),
        ("column_name", "sql_identifier"),
    ],
    "column_options": [
        ("table_catalog", "sql_identifier"),
        ("table_schema", "sql_identifier"),
        ("table_name", "sql_identifier"),
        ("column_name", "sql_identifier"),
        ("option_name", "sql_identifier"),
        ("option_value", "character_data"),
    ],
    "column_privileges": [
        ("grantor", "sql_identifier"),
        ("grantee", "sql_identifier"),
        ("table_catalog", "sql_identifier"),
        ("table_schema", "sql_identifier"),
        ("table_name", "sql_identifier"),
        ("column_name", "sql_identifier"),
        ("privilege_type", "character_data"),
        ("is_grantable", "yes_or_no"),
    ],
    "column_udt_usage": [
        ("udt_catalog", "sql_identifier"),
        ("udt_schema", "sql_identifier"),
        ("udt_name", "sql_identifier"),
        ("table_catalog", "sql_identifier"),
        ("table_schema", "sql_identifier"),
        ("table_name", "sql_identifier"),
        ("column_name", "sql_identifier"),
    ],
    "columns": [
        ("table_catalog", "sql_identifier"),
        ("table_schema", "sql_identifier"),
        ("table_name", "sql_identifier"),
        ("column_name", "sql_identifier"),
        ("ordinal_position", "cardinal_number"),
        ("column_default", "character_data"),
        ("is_nullable", "yes_or_no"),
        ("data_type", "character_data"),
        ("character_maximum_length", "cardinal_number"),
        ("character_octet_length", "cardinal_number"),
        ("numeric_precision", "cardinal_number"),
        ("numeric_precision_radix", "cardinal_number"),
        ("numeric_scale", "cardinal_number"),
        ("datetime_precision", "cardinal_number"),
        ("interval_type", "character_data"),
        ("interval_precision", "cardinal_number"),
        ("character_set_catalog", "sql_identifier"),
        ("character_set_schema", "sql_identifier"),
        ("character_set_name", "sql_identifier"),
        ("collation_catalog", "sql_identifier"),
        ("collation_schema", "sql_identifier"),
        ("collation_name", "sql_identifier"),
        ("domain_catalog", "sql_identifier"),
        ("domain_schema", "sql_identifier"),
        ("domain_name", "sql_identifier"),
        ("udt_catalog", "sql_identifier"),
        ("udt_schema", "sql_identifier"),
        ("udt_name", "sql_identifier"),
        ("scope_catalog", "sql_identifier"),
        ("scope_schema", "sql_identifier"),
        ("scope_name", "sql_identifier"),
        ("maximum_cardinality", "cardinal_number"),
        ("dtd_identifier", "sql_identifier"),
        ("is_self_referencing", "yes_or_no"),
        ("is_identity", "yes_or_no"),
        ("identity_generation", "character_data"),
        ("identity_start", "character_data"),
        ("identity_increment", "character_data"),
        ("identity_maximum", "character_data"),
        ("identity_minimum", "character_data"),
        ("identity_cycle", "yes_or_no"),
        ("is_generated", "character_data"),
        ("generation_expression", "character_data"),
        ("is_updatable", "yes_or_no"),
    ],
    "constraint_column_usage": [
        ("table_catalog", "sql_identifier"),
        ("table_schema", "sql_identifier"),
        ("table_name", "sql_identifier"),
        ("column_name", "sql_identifier"),
        ("constraint_catalog", "sql_identifier"),
        ("constraint_schema", "sql_identifier"),
        ("constraint_name", "sql_identifier"),
    ],
    "constraint_table_usage": [
        ("table_catalog", "sql_identifier"),
        ("table_schema", "sql_identifier"),
        ("table_name", "sql_identifier"),
        ("constraint_catalog", "sql_identifier"),
        ("constraint_schema", "sql_identifier"),
        ("constraint_name", "sql_identifier"),
    ],
    "data_type_privileges": [
        ("object_catalog", "sql_identifier"),
        ("object_schema", "sql_identifier"),
        ("object_name", "sql_identifier"),
        ("object_type", "character_data"),
        ("dtd_identifier", "sql_identifier"),
    ],
    "domain_constraints": [
        ("constraint_catalog", "sql_identifier"),
        ("constraint_schema", "sql_identifier"),
        ("constraint_name", "sql_identifier"),
        ("domain_catalog", "sql_identifier"),
        ("domain_schema", "sql_identifier"),
        ("domain_name", "sql_identifier"),
        ("is_deferrable", "yes_or_no"),
        ("initially_deferred", "yes_or_no"),
    ],
    "domain_udt_usage": [
        ("udt_catalog", "sql_identifier"),
        ("udt_schema", "sql_identifier"),
        ("udt_name", "sql_identifier"),
        ("domain_catalog", "sql_identifier"),
        ("domain_schema", "sql_identifier"),
        ("domain_name", "sql_identifier"),
    ],
    "domains": [
        ("domain_catalog", "sql_identifier"),
        ("domain_schema", "sql_identifier"),
        ("domain_name", "sql_identifier"),
        ("data_type", "character_data"),
        ("character_maximum_length", "cardinal_number"),
        ("character_octet_length", "cardinal_number"),
        ("character_set_catalog", "sql_identifier"),
        ("character_set_schema", "sql_identifier"),
        ("character_set_name", "sql_identifier"),
        ("collation_catalog", "sql_identifier"),
        ("collation_schema", "sql_identifier"),
        ("collation_name", "sql_identifier"),
        ("numeric_precision", "cardinal_number"),
        ("numeric_precision_radix", "cardinal_number"),
        ("numeric_scale", "cardinal_number"),
        ("datetime_precision", "cardinal_number"),
        ("interval_type", "character_data"),
        ("interval_precision", "cardinal_number"),
        ("domain_default", "character_data"),
        ("udt_catalog", "sql_identifier"),
        ("udt_schema", "sql_identifier"),
        ("udt_name", "sql_identifier"),
        ("scope_catalog", "sql_identifier"),
        ("scope_schema", "sql_identifier"),
        ("scope_name", "sql_identifier"),
        ("maximum_cardinality", "cardinal_number"),
        ("dtd_identifier", "sql_identifier"),
    ],
    "element_types": [
        ("object_catalog", "sql_identifier"),
        ("object_schema", "sql_identifier"),
        ("object_name", "sql_identifier"),
        ("object_type", "character_data"),
        ("collection_type_identifier", "sql_identifier"),
        ("data_type", "character_data"),
        ("character_maximum_length", "cardinal_number"),
        ("character_octet_length", "cardinal_number"),
        ("character_set_catalog", "sql_identifier"),
        ("character_set_schema", "sql_identifier"),
        ("character_set_name", "sql_identifier"),
        ("collation_catalog", "sql_identifier"),
        ("collation_schema", "sql_identifier"),
        ("collation_name", "sql_identifier"),
        ("numeric_precision", "cardinal_number"),
        ("numeric_precision_radix", "cardinal_number"),
        ("numeric_scale", "cardinal_number"),
        ("datetime_precision", "cardinal_number"),
        ("interval_type", "character_data"),
        ("interval_precision", "cardinal_number"),
        ("domain_default", "character_data"),
        ("udt_catalog", "sql_identifier"),
        ("udt_schema", "sql_identifier"),
        ("udt_name", "sql_identifier"),
        ("scope_catalog", "sql_identifier"),
        ("scope_schema", "sql_identifier"),
        ("scope_name", "sql_identifier"),
        ("maximum_cardinality", "cardinal_number"),
        ("dtd_identifier", "sql_identifier"),
    ],
    "enabled_roles": [("role_name", "sql_identifier")],
    "foreign_data_wrapper_options": [
        ("foreign_data_wrapper_catalog", "sql_identifier"),
        ("foreign_data_wrapper_name", "sql_identifier"),
        ("option_name", "sql_identifier"),
        ("option_value", "character_data"),
    ],
    "foreign_data_wrappers": [
        ("foreign_data_wrapper_catalog", "sql_identifier"),
        ("foreign_data_wrapper_name", "sql_identifier"),
        ("authorization_identifier", "sql_identifier"),
        ("library_name", "character_data"),
        ("foreign_data_wrapper_language", "character_data"),
    ],
    "foreign_server_options": [
        ("foreign_server_catalog", "sql_identifier"),
        ("foreign_server_name", "sql_identifier"),
        ("option_name", "sql_identifier"),
        ("option_value", "character_data"),
    ],
    "foreign_servers": [
        ("foreign_server_catalog", "sql_identifier"),
        ("foreign_server_name", "sql_identifier"),
        ("foreign_data_wrapper_catalog", "sql_identifier"),
        ("foreign_data_wrapper_name", "sql_identifier"),
        ("foreign_server_type", "character_data"),
        ("foreign_server_version", "character_data"),
        ("authorization_identifier", "sql_identifier"),
    ],
    "foreign_table_options": [
        ("foreign_table_catalog", "sql_identifier"),
        ("foreign_table_schema", "sql_identifier"),
        ("foreign_table_name", "sql_identifier"),
        ("option_name", "sql_identifier"),
        ("option_value", "character_data"),
    ],
    "foreign_tables": [
        ("foreign_table_catalog", "sql_identifier"),
        ("foreign_table_schema", "sql_identifier"),
        ("foreign_table_name", "sql_identifier"),
        ("foreign_server_catalog", "sql_identifier"),
        ("foreign_server_name", "sql_identifier"),
    ],
    "information_schema_catalog_name": [("catalog_name", "sql_identifier")],
    "key_column_usage": [
        ("constraint_catalog", "sql_identifier"),
        ("constraint_schema", "sql_identifier"),
        ("constraint_name", "sql_identifier"),
        ("table_catalog", "sql_identifier"),
        ("table_schema", "sql_identifier"),
        ("table_name", "sql_identifier"),
        ("column_name", "sql_identifier"),
        ("ordinal_position", "cardinal_number"),
        ("position_in_unique_constraint", "cardinal_number"),
    ],
    "parameters": [
        ("specific_catalog", "sql_identifier"),
        ("specific_schema", "sql_identifier"),
        ("specific_name", "sql_identifier"),
        ("ordinal_position", "cardinal_number"),
        ("parameter_mode", "character_data"),
        ("is_result", "yes_or_no"),
        ("as_locator", "yes_or_no"),
        ("parameter_name", "sql_identifier"),
        ("data_type", "character_data"),
        ("character_maximum_length", "cardinal_number"),
        ("character_octet_length", "cardinal_number"),
        ("character_set_catalog", "sql_identifier"),
        ("character_set_schema", "sql_identifier"),
        ("character_set_name", "sql_identifier"),
        ("collation_catalog", "sql_identifier"),
        ("collation_schema", "sql_identifier"),
        ("collation_name", "sql_identifier"),
        ("numeric_precision", "cardinal_number"),
        ("numeric_precision_radix", "cardinal_number"),
        ("numeric_scale", "cardinal_number"),
        ("datetime_precision", "cardinal_number"),
        ("interval_type", "character_data"),
        ("interval_precision", "cardinal_number"),
        ("udt_catalog", "sql_identifier"),
        ("udt_schema", "sql_identifier"),
        ("udt_name", "sql_identifier"),
        ("scope_catalog", "sql_identifier"),
        ("scope_schema", "sql_identifier"),
        ("scope_name", "sql_identifier"),
        ("maximum_cardinality", "cardinal_number"),
        ("dtd_identifier", "sql_identifier"),
        ("parameter_default", "character_data"),
    ],
    "referential_constraints": [
        ("constraint_catalog", "sql_identifier"),
        ("constraint_schema", "sql_identifier"),
        ("constraint_name", "sql_identifier"),
        ("unique_constraint_catalog", "sql_identifier"),
        ("unique_constraint_schema", "sql_identifier"),
        ("unique_constraint_name", "sql_identifier"),
        ("match_option", "character_data"),
        ("update_rule", "character_data"),
        ("delete_rule", "character_data"),
    ],
    "role_column_grants": [
        ("grantor", "sql_identifier"),
        ("grantee", "sql_identifier"),
        ("table_catalog", "sql_identifier"),
        ("table_schema", "sql_identifier"),
        ("table_name", "sql_identifier"),
        ("column_name", "sql_identifier"),
        ("privilege_type", "character_data"),
        ("is_grantable", "yes_or_no"),
    ],
    "role_routine_grants": [
        ("grantor", "sql_identifier"),
        ("grantee", "sql_identifier"),
        ("specific_catalog", "sql_identifier"),
        ("specific_schema", "sql_identifier"),
        ("specific_name", "sql_identifier"),
        ("routine_catalog", "sql_identifier"),
        ("routine_schema", "sql_identifier"),
        ("routine_name", "sql_identifier"),
        ("privilege_type", "character_data"),
        ("is_grantable", "yes_or_no"),
    ],
    "role_table_grants": [
        ("grantor", "sql_identifier"),
        ("grantee", "sql_identifier"),
        ("table_catalog", "sql_identifier"),
        ("table_schema", "sql_identifier"),
        ("table_name", "sql_identifier"),
        ("privilege_type", "character_data"),
        ("is_grantable", "yes_or_no"),
        ("with_hierarchy", "yes_or_no"),
    ],
    "role_udt_grants": [
        ("grantor", "sql_identifier"),
        ("grantee", "sql_identifier"),
        ("udt_catalog", "sql_identifier"),
        ("udt_schema", "sql_identifier"),
        ("udt_name", "sql_identifier"),
        ("privilege_type", "character_data"),
        ("is_grantable", "yes_or_no"),
    ],
    "role_usage_grants": [
        ("grantor", "sql_identifier"),
        ("grantee", "sql_identifier"),
        ("object_catalog", "sql_identifier"),
        ("object_schema", "sql_identifier"),
        ("object_name", "sql_identifier"),
        ("object_type", "character_data"),
        ("privilege_type", "character_data"),
        ("is_grantable", "yes_or_no"),
    ],
    "routine_privileges": [
        ("grantor", "sql_identifier"),
        ("grantee", "sql_identifier"),
        ("specific_catalog", "sql_identifier"),
        ("specific_schema", "sql_identifier"),
        ("specific_name", "sql_identifier"),
        ("routine_catalog", "sql_identifier"),
        ("routine_schema", "sql_identifier"),
        ("routine_name", "sql_identifier"),
        ("privilege_type", "character_data"),
        ("is_grantable", "yes_or_no"),
    ],
    "routines": [
        ("specific_catalog", "sql_identifier"),
        ("specific_schema", "sql_identifier"),
        ("specific_name", "sql_identifier"),
        ("routine_catalog", "sql_identifier"),
        ("routine_schema", "sql_identifier"),
        ("routine_name", "sql_identifier"),
        ("routine_type", "character_data"),
        ("module_catalog", "sql_identifier"),
        ("module_schema", "sql_identifier"),
        ("module_name", "sql_identifier"),
        ("udt_catalog", "sql_identifier"),
        ("udt_schema", "sql_identifier"),
        ("udt_name", "sql_identifier"),
        ("data_type", "character_data"),
        ("character_maximum_length", "cardinal_number"),
        ("character_octet_length", "cardinal_number"),
        ("character_set_catalog", "sql_identifier"),
        ("character_set_schema", "sql_identifier"),
        ("character_set_name", "sql_identifier"),
        ("collation_catalog", "sql_identifier"),
        ("collation_schema", "sql_identifier"),
        ("collation_name", "sql_identifier"),
        ("numeric_precision", "cardinal_number"),
        ("numeric_precision_radix", "cardinal_number"),
        ("numeric_scale", "cardinal_number"),
        ("datetime_precision", "cardinal_number"),
        ("interval_type", "character_data"),
        ("interval_precision", "cardinal_number"),
        ("type_udt_catalog", "sql_identifier"),
        ("type_udt_schema", "sql_identifier"),
        ("type_udt_name", "sql_identifier"),
        ("scope_catalog", "sql_identifier"),
        ("scope_schema", "sql_identifier"),
        ("scope_name", "sql_identifier"),
        ("maximum_cardinality", "cardinal_number"),
        ("dtd_identifier", "sql_identifier"),
        ("routine_body", "character_data"),
        ("routine_definition", "character_data"),
        ("external_name", "character_data"),
        ("external_language", "character_data"),
        ("parameter_style", "character_data"),
        ("is_deterministic", "yes_or_no"),
        ("sql_data_access", "character_data"),
        ("is_null_call", "yes_or_no"),
        ("sql_path", "character_data"),
        ("schema_level_routine", "yes_or_no"),
        ("max_dynamic_result_sets", "cardinal_number"),
        ("is_user_defined_cast", "yes_or_no"),
        ("is_implicitly_invocable", "yes_or_no"),
        ("security_type", "character_data"),
        ("to_sql_specific_catalog", "sql_identifier"),
        ("to_sql_specific_schema", "sql_identifier"),
        ("to_sql_specific_name", "sql_identifier"),
        ("as_locator", "yes_or_no"),
        ("created", "time_stamp"),
        ("last_altered", "time_stamp"),
        ("new_savepoint_level", "yes_or_no"),
        ("is_udt_dependent", "yes_or_no"),
        ("result_cast_from_data_type", "character_data"),
        ("result_cast_as_locator", "yes_or_no"),
        ("result_cast_char_max_length", "cardinal_number"),
        ("result_cast_char_octet_length", "cardinal_number"),
        ("result_cast_char_set_catalog", "sql_identifier"),
        ("result_cast_char_set_schema", "sql_identifier"),
        ("result_cast_char_set_name", "sql_identifier"),
        ("result_cast_collation_catalog", "sql_identifier"),
        ("result_cast_collation_schema", "sql_identifier"),
        ("result_cast_collation_name", "sql_identifier"),
        ("result_cast_numeric_precision", "cardinal_number"),
        ("result_cast_numeric_precision_radix", "cardinal_number"),
        ("result_cast_numeric_scale", "cardinal_number"),
        ("result_cast_datetime_precision", "cardinal_number"),
        ("result_cast_interval_type", "character_data"),
        ("result_cast_interval_precision", "cardinal_number"),
        ("result_cast_type_udt_catalog", "sql_identifier"),
        ("result_cast_type_udt_schema", "sql_identifier"),
        ("result_cast_type_udt_name", "sql_identifier"),
        ("result_cast_scope_catalog", "sql_identifier"),
        ("result_cast_scope_schema", "sql_identifier"),
        ("result_cast_scope_name", "sql_identifier"),
        ("result_cast_maximum_cardinality", "cardinal_number"),
        ("result_cast_dtd_identifier", "sql_identifier"),
    ],
    "schemata": [
        ("catalog_name", "sql_identifier"),
        ("schema_name", "sql_identifier"),
        ("schema_owner", "sql_identifier"),
        ("default_character_set_catalog", "sql_identifier"),
        ("default_character_set_schema", "sql_identifier"),
        ("default_character_set_name", "sql_identifier"),
        ("sql_path", "character_data"),
    ],
    "sequences": [
        ("sequence_catalog", "sql_identifier"),
        ("sequence_schema", "sql_identifier"),
        ("sequence_name", "sql_identifier"),
        ("data_type", "character_data"),
        ("numeric_precision", "cardinal_number"),
        ("numeric_precision_radix", "cardinal_number"),
        ("numeric_scale", "cardinal_number"),
        ("start_value", "character_data"),
        ("minimum_value", "character_data"),
        ("maximum_value", "character_data"),
        ("increment", "character_data"),
        ("cycle_option", "yes_or_no"),
    ],
    "sql_features": [
        ("feature_id", "character_data"),
        ("feature_name", "character_data"),
        ("sub_feature_id", "character_data"),
        ("sub_feature_name", "character_data"),
        ("is_supported", "yes_or_no"),
        ("is_verified_by", "character_data"),
        ("comments", "character_data"),
    ],
    "sql_implementation_info": [
        ("implementation_info_id", "character_data"),
        ("implementation_info_name", "character_data"),
        ("integer_value", "cardinal_number"),
        ("character_value", "character_data"),
        ("comments", "character_data"),
    ],
    "sql_languages": [
        ("sql_language_source", "character_data"),
        ("sql_language_year", "character_data"),
        ("sql_language_conformance", "character_data"),
        ("sql_language_integrity", "character_data"),
        ("sql_language_implementation", "character_data"),
        ("sql_language_binding_style", "character_data"),
        ("sql_language_programming_language", "character_data"),
    ],
    "sql_packages": [
        ("feature_id", "character_data"),
        ("feature_name", "character_data"),
        ("is_supported", "yes_or_no"),
        ("is_verified_by", "character_data"),
        ("comments", "character_data"),
    ],
    "sql_parts": [
        ("feature_id", "character_data"),
        ("feature_name", "character_data"),
        ("is_supported", "yes_or_no"),
        ("is_verified_by", "character_data"),
        ("comments", "character_data"),
    ],
    "sql_sizing": [
        ("sizing_id", "cardinal_number"),
        ("sizing_name", "character_data"),
        ("supported_value", "cardinal_number"),
        ("comments", "character_data"),
    ],
    "sql_sizing_profiles": [
        ("sizing_id", "cardinal_number"),
        ("sizing_name", "character_data"),
        ("profile_id", "character_data"),
        ("required_value", "cardinal_number"),
        ("comments", "character_data"),
    ],
    "table_constraints": [
        ("constraint_catalog", "sql_identifier"),
        ("constraint_schema", "sql_identifier"),
        ("constraint_name", "sql_identifier"),
        ("table_catalog", "sql_identifier"),
        ("table_schema", "sql_identifier"),
        ("table_name", "sql_identifier"),
        ("constraint_type", "character_data"),
        ("is_deferrable", "yes_or_no"),
        ("initially_deferred", "yes_or_no"),
        ("enforced", "yes_or_no"),
    ],
    "table_privileges": [
        ("grantor", "sql_identifier"),
        ("grantee", "sql_identifier"),
        ("table_catalog", "sql_identifier"),
        ("table_schema", "sql_identifier"),
        ("table_name", "sql_identifier"),
        ("privilege_type", "character_data"),
        ("is_grantable", "yes_or_no"),
        ("with_hierarchy", "yes_or_no"),
    ],
    "tables": [
        ("table_catalog", "sql_identifier"),
        ("table_schema", "sql_identifier"),
        ("table_name", "sql_identifier"),
        ("table_type", "character_data"),
        ("self_referencing_column_name", "sql_identifier"),
        ("reference_generation", "character_data"),
        ("user_defined_type_catalog", "sql_identifier"),
        ("user_defined_type_schema", "sql_identifier"),
        ("user_defined_type_name", "sql_identifier"),
        ("is_insertable_into", "yes_or_no"),
        ("is_typed", "yes_or_no"),
        ("commit_action", "character_data"),
    ],
    "transforms": [
        ("udt_catalog", "sql_identifier"),
        ("udt_schema", "sql_identifier"),
        ("udt_name", "sql_identifier"),
        ("specific_catalog", "sql_identifier"),
        ("specific_schema", "sql_identifier"),
        ("specific_name", "sql_identifier"),
        ("group_name", "sql_identifier"),
        ("transform_type", "character_data"),
    ],
    "triggered_update_columns": [
        ("trigger_catalog", "sql_identifier"),
        ("trigger_schema", "sql_identifier"),
        ("trigger_name", "sql_identifier"),
        ("event_object_catalog", "sql_identifier"),
        ("event_object_schema", "sql_identifier"),
        ("event_object_table", "sql_identifier"),
        ("event_object_column", "sql_identifier"),
    ],
    "triggers": [
        ("trigger_catalog", "sql_identifier"),
        ("trigger_schema", "sql_identifier"),
        ("trigger_name", "sql_identifier"),
        ("event_manipulation", "character_data"),
        ("event_object_catalog", "sql_identifier"),
        ("event_object_schema", "sql_identifier"),
        ("event_object_table", "sql_identifier"),
        ("action_order", "cardinal_number"),
        ("action_condition", "character_data"),
        ("action_statement", "character_data"),
        ("action_orientation", "character_data"),
        ("action_timing", "character_data"),
        ("action_reference_old_table", "sql_identifier"),
        ("action_reference_new_table", "sql_identifier"),
        ("action_reference_old_row", "sql_identifier"),
        ("action_reference_new_row", "sql_identifier"),
        ("created", "time_stamp"),
    ],
    "udt_privileges": [
        ("grantor", "sql_identifier"),
        ("grantee", "sql_identifier"),
        ("udt_catalog", "sql_identifier"),
        ("udt_schema", "sql_identifier"),
        ("udt_name", "sql_identifier"),
        ("privilege_type", "character_data"),
        ("is_grantable", "yes_or_no"),
    ],
    "usage_privileges": [
        ("grantor", "sql_identifier"),
        ("grantee", "sql_identifier"),
        ("object_catalog", "sql_identifier"),
        ("object_schema", "sql_identifier"),
        ("object_name", "sql_identifier"),
        ("object_type", "character_data"),
        ("privilege_type", "character_data"),
        ("is_grantable", "yes_or_no"),
    ],
    "user_defined_types": [
        ("user_defined_type_catalog", "sql_identifier"),
        ("user_defined_type_schema", "sql_identifier"),
        ("user_defined_type_name", "sql_identifier"),
        ("user_defined_type_category", "character_data"),
        ("is_instantiable", "yes_or_no"),
        ("is_final", "yes_or_no"),
        ("ordering_form", "character_data"),
        ("ordering_category", "character_data"),
        ("ordering_routine_catalog", "sql_identifier"),
        ("ordering_routine_schema", "sql_identifier"),
        ("ordering_routine_name", "sql_identifier"),
        ("reference_type", "character_data"),
        ("data_type", "character_data"),
        ("character_maximum_length", "cardinal_number"),
        ("character_octet_length", "cardinal_number"),
        ("character_set_catalog", "sql_identifier"),
        ("character_set_schema", "sql_identifier"),
        ("character_set_name", "sql_identifier"),
        ("collation_catalog", "sql_identifier"),
        ("collation_schema", "sql_identifier"),
        ("collation_name", "sql_identifier"),
        ("numeric_precision", "cardinal_number"),
        ("numeric_precision_radix", "cardinal_number"),
        ("numeric_scale", "cardinal_number"),
        ("datetime_precision", "cardinal_number"),
        ("interval_type", "character_data"),
        ("interval_precision", "cardinal_number"),
        ("source_dtd_identifier", "sql_identifier"),
        ("ref_dtd_identifier", "sql_identifier"),
    ],
    "user_mapping_options": [
        ("authorization_identifier", "sql_identifier"),
        ("foreign_server_catalog", "sql_identifier"),
        ("foreign_server_name", "sql_identifier"),
        ("option_name", "sql_identifier"),
        ("option_value", "character_data"),
    ],
    "user_mappings": [
        ("authorization_identifier", "sql_identifier"),
        ("foreign_server_catalog", "sql_identifier"),
        ("foreign_server_name", "sql_identifier"),
    ],
    "view_column_usage": [
        ("view_catalog", "sql_identifier"),
        ("view_schema", "sql_identifier"),
        ("view_name", "sql_identifier"),
        ("table_catalog", "sql_identifier"),
        ("table_schema", "sql_identifier"),
        ("table_name", "sql_identifier"),
        ("column_name", "sql_identifier"),
    ],
    "view_routine_usage": [
        ("table_catalog", "sql_identifier"),
        ("table_schema", "sql_identifier"),
        ("table_name", "sql_identifier"),
        ("specific_catalog", "sql_identifier"),
        ("specific_schema", "sql_identifier"),
        ("specific_name", "sql_identifier"),
    ],
    "view_table_usage": [
        ("view_catalog", "sql_identifier"),
        ("view_schema", "sql_identifier"),
        ("view_name", "sql_identifier"),
        ("table_catalog", "sql_identifier"),
        ("table_schema", "sql_identifier"),
        ("table_name", "sql_identifier"),
    ],
    "views": [
        ("table_catalog", "sql_identifier"),
        ("table_schema", "sql_identifier"),
        ("table_name", "sql_identifier"),
        ("view_definition", "character_data"),
        ("check_option", "character_data"),
        ("is_updatable", "yes_or_no"),
        ("is_insertable_into", "yes_or_no"),
        ("is_trigger_updatable", "yes_or_no"),
        ("is_trigger_deletable", "yes_or_no"),
        ("is_trigger_insertable_into", "yes_or_no"),
    ],
}

# retrived with:
r"""
WITH
columns AS (
    SELECT table_name, TO_JSON(ARRAY [column_name, domain_name]) AS col
    FROM information_schema.columns
    WHERE table_schema = 'information_schema'
      AND table_name NOT LIKE '\_pg%'
    ORDER BY table_name, ordinal_position
),
tables AS (
    SELECT table_name, JSON_AGG(col) cols
    FROM columns
    GROUP BY table_name
)
SELECT JSON_OBJECT_AGG(table_name, cols) FROM tables
"""
